version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'develop.ink-remix.blockchain-it.hr -> http://ink-plugin:3000, server.develop.ink-remix.blockchain-it.hr -> http://ink-server:65520'
      STAGE: 'production'
      WEBSOCKET: 'true'
    container_name: nginx
    networks:
      - ink-network

  ink-plugin:
    image: blockchainit/ink-plugin:latest
    container_name: ink-plugin
    networks:
      - ink-network
    ports:
      - "3000:80"

  ink-server:
    image: blockchainit/ink-server:latest
    container_name: ink-server
    networks:
      - ink-network
    ports:
      - "65520:65520"

networks:
  ink-network:
