version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'develop.ink-remix.blockchain-it.hr -> http://ink-remix-frontend-dev:10000, staging.ink-remix.blockchain-it.hr -> http://ink-remix-frontend-stag:10000, backend.develop.ink-remix.blockchain-it.hr -> http://ink-remix-backend-dev:10000, backend.staging.ink-remix.blockchain-it.hr -> http://ink-remix-backend-stag:10000'
      STAGE: 'production'
    container_name: nginx
    networks:
      - ink-remix


  ink-remix-frontend-dev:
    image: blockchainit/ink-backend:latest
    container_name: ink-remix-frontend-dev
    networks:
      - ink-remix

  ink-remix-frontend-stag:
    image: blockchainit/ink-frontend:latest
    container_name: ink-remix-frontend-stag
    networks:
      - ink-remix      

  ink-remix-backend-dev:
    image: blockchainit/ink-backend:latest
    container_name: ink-remix-backend-dev
    networks:
      - ink-remix

  # Update when staging is developed
  ink-remix-backend-stag:
    image: blockchainit/ink-backend:latest
    container_name: ink-remix-backend-stag
    networks:
      - ink-remix     

networks:
  ink-remix:
