version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'develop.ink-remix.blockchain-it.hr -> http://ink-remix-plugin-dev:10000, staging.ink-remix.blockchain-it.hr -> http://ink-remix-plugin-stag:10000, server.develop.ink-remix.blockchain-it.hr -> http://ink-remix-server-dev:10000, server.staging.ink-remix.blockchain-it.hr -> http://ink-remix-server-stag:10000'
      STAGE: 'production'
    container_name: nginx
    networks:
      - ink-remix


  ink-remix-plugin-dev:
    image: blockchainit/ink-plugin:latest
    container_name: ink-remix-plugin-dev
    networks:
      - ink-remix

  ink-remix-plugin-stag:
    image: blockchainit/ink-plugin:latest
    container_name: ink-remix-plugin-stag
    networks:
      - ink-remix      

  ink-remix-server-dev:
    image: blockchainit/ink-server:latest
    container_name: ink-remix-server-dev
    networks:
      - ink-remix

  # Update when staging is developed
  ink-remix-server-stag:
    image: blockchainit/ink-server:latest
    container_name: ink-remix-server-stag
    networks:
      - ink-remix     

networks:
  ink-remix:
